In [1]:
#Imports
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sqlalchemy import create_engine
from tkinter import *
from tkinter import filedialog
from tkinter import messagebox
from mto import save_db
filename = ''

In [15]:
# Function for opening the
# file explorer window
def browseFiles():
    globals()['filename'] = filedialog.askopenfilename(initialdir = "./",
                                          title = "Select a File",
                                          filetypes = (("Excel files",
                                                        "*.xls .xlsx .xlsm .xlsb .xlsb .odf .ods .odt*"),
                                                       ))
    # Change label contents
    label_file_explorer.configure(text="Selected File: "+filename)

# Create the root window
window = Tk()

# Set window title
window.title('MTO/SV EXCEL IMPORT TO DB')

# Set window size
window.geometry("500x200")

# Alert Box
def msgalert():
    conf_save=messagebox.askokcancel('Ok Cancel','Do you wish proceed?')
    if conf_save: 
        save_db(filename) 
        messagebox.showinfo(title='Ã‰ isso memo',message='Succeed')

# Create a File Explorer label
label_file_explorer = Label(window,
                            text = "MTO/SV Excel File Explorer",
                            height = 4,
                            fg = "blue")

button_save = Button(window,
                        text = "Send to db",
                        command = msgalert)

button_explore = Button(window,
                        text = "Browse Excel File",
                        command = browseFiles)
  
button_exit = Button(window,
                     text = "Exit",
                     command = window.destroy)



# Grid method is chosen for placing
# the widgets at respective positions
# in a table like structure by
# specifying rows and columns
label_file_explorer.grid(column = 0, row = 0, columnspan=15, padx=40)

button_save.grid(column = 1, row = 2, columnspan=10)
  
button_explore.grid(column = 1, row = 3, columnspan=10)
  
button_exit.grid(column = 1,row = 4, columnspan=10 )
  
# Let the window wait for any events
window.mainloop()

In [ ]:
#XLSX/EXCEL IMPORT
df = pd.read_excel('1 - 12042021.xlsx', skiprows=2)
df2 = pd.read_excel('2 - Meteo 01-09-2021.xlsx', skiprows=2)
df3 = pd.read_excel('3 - meteo 15-07-2021.xlsx', skiprows=2)
df4 = pd.read_excel('4 - meteo 22-08-2021.xlsx', skiprows=2)
df5 = pd.read_excel('5 - Meteo 28-06-2021.xlsx', skiprows=2)
df6 = pd.read_excel('6 - 03082020.xlsx', skiprows=2)
df = df.replace("Timeout", 0)

Error: Session cannot generate requests

In [35]:
#RENAME DATAFRAME
df.rename(columns={"Timestamp": "datetime_", 
                   "visibility\n601 [m] Cur": "visibility", "ambient temperature\n100 [Â°C] Cur": "ambient_temperature",
                   "temperature\n100 [Â°C] Cur": "temperature", "wind speed\n405 [km/h] Cur": "wind_speed", "wind direction\n500 [Â°] Cur": "wind_direction", 
                   "precipitation absol.\n600 [l/mÂ²] Cur": "absolute_precipitation",
                   "temperature\n100 [Â°C] Cur.1": "temperature", "wind speed\n405 [km/h] Cur.1": "wind_speed", "wind direction\n500 [Â°] Cur.1": "wind_direction", 
                   "precipitation absol.\n600 [l/mÂ²] Cur.1": "absolute_precipitation",
                   "road temperature\n100 [norm value] Cur": "road_temperature"
                   }, inplace=True)
df

,datetime_,visibility,ambient_temperature,temperature,wind_speed,wind_direction,absolute_precipitation,temperature,wind_speed,wind_direction,absolute_precipitation,road_temperature
0,2020-09-28 19:15:16.328,2000,29.07797,28.53674,8.712472,29.18288,607.02,27.99643,5.959532,354.71310,1003.11,44632
1,2020-09-28 19:25:16.328,2000,28.87499,28.34637,3.088818,47.60624,607.02,27.80622,4.632154,19.88260,1003.11,44281
2,2020-09-28 19:35:16.327,2000,28.67481,28.25570,6.935800,29.36514,607.02,27.65645,5.363084,15.80396,1003.11,43976
3,2020-09-28 19:45:16.327,2000,28.57430,28.28563,3.642190,359.87760,607.02,27.62427,9.417500,352.17450,1003.11,43726
4,2020-09-28 19:55:16.327,2000,28.47350,27.95006,3.659162,37.82709,607.02,27.72074,4.726597,304.21710,1003.11,43501
...,...,...,...,...,...,...,...,...,...,...,...,...
28179,2021-04-12 11:42:53.971,2000,34.32373,28.72500,6.510491,187.82290,831.75,0.00000,0.000000,0.00000,0.00,47712
28180,2021-04-12 11:52:53.970,172,34.55962,28.86986,9.057920,103.60590,831.75,0.00000,0.000000,0.00000,0.00,48627
28181,2021-04-12 12:02:53.970,2000,34.79428,29.41179,1.817147,339.99120,831.75,0.00000,0.000000,0.00000,0.00,48514
28182,2021-04-12 12:12:53.970,2000,36.12343,29.65355,4.817945,89.27724,831.75,0.00000,0.000000,0.00000,0.00,49559
28183,2021-04-12 12:22:53.971,2000,35.87781,29.96116,3.131297,91.09693,831.75,0.00000,0.000000,0.00000,0.00,49531

In [68]:
#SVs 
sv3=df.iloc[:,7:11].copy()
sv1=df.iloc[:,12:16].copy()
sv5=df.iloc[:,16:20].copy()
sv3["datetime_"] = df["datetime_"]
sv3

,temperature,wind_speed,wind_direction,absolute_precipitation,datetime_
0,27.99643,5.959532,354.71310,1003.11,2020-09-28 19:15:16.328
1,27.80622,4.632154,19.88260,1003.11,2020-09-28 19:25:16.328
2,27.65645,5.363084,15.80396,1003.11,2020-09-28 19:35:16.327
3,27.62427,9.417500,352.17450,1003.11,2020-09-28 19:45:16.327
4,27.72074,4.726597,304.21710,1003.11,2020-09-28 19:55:16.327
...,...,...,...,...,...
28179,0.00000,0.000000,0.00000,0.00,2021-04-12 11:42:53.971
28180,0.00000,0.000000,0.00000,0.00,2021-04-12 11:52:53.970
28181,0.00000,0.000000,0.00000,0.00,2021-04-12 12:02:53.970
28182,0.00000,0.000000,0.00000,0.00,2021-04-12 12:12:53.970
28183,0.00000,0.000000,0.00000,0.00,2021-04-12 12:22:53.971

In [67]:
#SVMTO
svmeteo = df.iloc[:,:7].copy()
svmeteo["road_temperature"] = df["road_temperature"]
svmeteo

,datetime_,visibility,ambient_temperature,temperature,wind_speed,wind_direction,absolute_precipitation,road_temperature
0,2020-09-28 19:15:16.328,2000,29.07797,28.53674,8.712472,29.18288,607.02,44632
1,2020-09-28 19:25:16.328,2000,28.87499,28.34637,3.088818,47.60624,607.02,44281
2,2020-09-28 19:35:16.327,2000,28.67481,28.25570,6.935800,29.36514,607.02,43976
3,2020-09-28 19:45:16.327,2000,28.57430,28.28563,3.642190,359.87760,607.02,43726
4,2020-09-28 19:55:16.327,2000,28.47350,27.95006,3.659162,37.82709,607.02,43501
...,...,...,...,...,...,...,...,...
28179,2021-04-12 11:42:53.971,2000,34.32373,28.72500,6.510491,187.82290,831.75,47712
28180,2021-04-12 11:52:53.970,172,34.55962,28.86986,9.057920,103.60590,831.75,48627
28181,2021-04-12 12:02:53.970,2000,34.79428,29.41179,1.817147,339.99120,831.75,48514
28182,2021-04-12 12:12:53.970,2000,36.12343,29.65355,4.817945,89.27724,831.75,49559
28183,2021-04-12 12:22:53.971,2000,35.87781,29.96116,3.131297,91.09693,831.75,49531

In [15]:
user = "root"
passwd = "trcvbr18"
host = "localhost"
port = 3306
db = "tracevia_app"

#Create connection to the MySQL database
engine = create_engine(f'mysql://{user}:{passwd}@{host}:{port}/{db}')
con = engine.connect()

In [71]:
#Adjust SVs COLUMNS
# svlist = sv3.columns.tolist()
# svlist.insert(0, svlist.pop(3))
# svlist.insert(1, svlist.pop(2))
# svlist.insert(2, svlist.pop(3))
# #sv3[svlist]

svmeteo.to_sql(con=con, schema='tracevia_app', name='mto_data', if_exists='append', index=False) 
sv3.to_sql(con=con, schema='tracevia_app', name='sv_data', if_exists='append', index=False)

In [ ]:
#Adjust MTO COLUMNS
# svmeteolist = svmeteo.columns.tolist()
# svmeteolist.insert(6, svmeteolist.pop(1))
# svmeteolist.insert(1, svmeteolist.pop(5))
# svmeteolist.insert(2, svmeteolist.pop(4))
# svmeteolist.insert(3, svmeteolist.pop(5))
# svmeteolist.insert(4, svmeteolist.pop(5))
# svmeteo[svmeteolist]